# Generated by Django 5.1.3 on 2024-12-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('SSN', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('SSN', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('specialty', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('SSN', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Gender', models.CharField(max_length=10)),
                ('dateOfBirth', models.DateField()),
                ('emergencyContactName', models.CharField(blank=True, max_length=50, null=True)),
                ('emergencyContactPhone', models.CharField(blank=True, max_length=10, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
