# Generated by Django 5.1.3 on 2024-12-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0005_rename_gender_patient_gender_remove_doctor_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
