# Generated by Django 5.1.3 on 2024-12-17 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0006_doctor_password_patient_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='password',
        ),
        migrations.AlterField(
            model_name='patient',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Dpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dpi.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Care',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.CharField(max_length=500)),
                ('dpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpi.dpi')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=100)),
                ('dpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpi.dpi')),
            ],
        ),
        migrations.CreateModel(
            name='prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issueDate', models.CharField(max_length=10)),
                ('validationDate', models.CharField(max_length=10)),
                ('dpi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dpi.dpi')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('bloodwork', 'Bloodwork'), ('scan', 'Scan')], max_length=50)),
                ('issueDate', models.DateField()),
                ('conductionDate', models.DateField()),
                ('status', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpi.dpi')),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='examinations/')),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scan', to='dpi.test')),
            ],
        ),
        migrations.CreateModel(
            name='Bloodwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.TextField()),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bloodwork', to='dpi.test')),
            ],
        ),
    ]
