# Generated by Django 5.1.3 on 2024-12-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0007_remove_doctor_password_remove_patient_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('SSN', models.CharField(max_length=50)),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('email', models.CharField(max_length=50, null=True, unique=True)),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
    ]
