# Generated by Django 5.1.3 on 2024-12-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0008_administrative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrative',
            name='SSN',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='SSN',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='SSN',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
