# Generated by Django 5.1.3 on 2024-12-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0009_alter_administrative_ssn_alter_doctor_ssn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dateOfBirth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergencyContactName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergencyContactPhone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
