# Generated by Django 5.1.3 on 2024-12-20 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0010_patient_address_alter_patient_dateofbirth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='dpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpi.dpi'),
        ),
    ]
