# Generated by Django 5.1.3 on 2024-12-20 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0011_alter_prescription_dpi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrative',
            name='email',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
    ]
