# Generated by Django 5.1.3 on 2024-12-21 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0014_laborantin_nurse_radiologist'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='actors',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dpi.usercredentials'),
        ),
    ]
