# Generated by Django 5.1.3 on 2024-12-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0017_remove_administrative_hospital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrative',
            name='email',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='laborantin',
            name='email',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='nurse',
            name='email',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='radiologist',
            name='email',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
