# Generated by Django 5.1.3 on 2024-12-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0018_administrative_email_doctor_email_laborantin_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='administrative_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='doctor_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='laborantin_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='nurse_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='radiologist_count',
            field=models.IntegerField(default=0),
        ),
    ]
