# Generated by Django 5.1.3 on 2024-12-25 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0019_hospital_administrative_count_hospital_doctor_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('SSN', models.CharField(max_length=50, unique=True)),
                ('dateAdded', models.DateTimeField(auto_now_add=True, null=True)),
                ('email', models.CharField(max_length=50, null=True, unique=True)),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administrator', to='dpi.hospital')),
            ],
            options={
                'ordering': ['-dateAdded'],
                'abstract': False,
            },
        ),
    ]
